# Generated by Django 4.1.5 on 2023-02-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
